### PR TITLE
Add linters

### PR DESCRIPTION
**Pull request by vanillainanutshell**
# What was done in this PR:

- Create an index.js file and set an array of some simple to do tasks,
- Write a function to iterate over the tasks array and populate an HTML list item element for each task,
- On page load render the dynamically created list of tasks in the dedicated placeholder,
- Create a style.css and set rules for the To Do List.

### CODE REVIEW

**Comment by moise10r** [comment]
What's wrong?

**Comment by vanillainanutshell** [comment]
> What's wrong?

Im having problems with an eslint error that isn't appearing on my local

**Comment by moise10r** [comment]
Fix it then am waiting.

**Comment by vanillainanutshell** [comment]
> Fix it then am waiting.

Ok, I couldn't fix it, would you give me some light?
I would rather not use rules to pass through if it's possible.

**Review by moise10r — CHANGES_REQUESTED** [review]
### Hi **@Vanillainautshell,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Great job on adding linters to your project👏 . However, they are not passing yet, kindly fix this issue it is always better to have all linter checks passing, this helps you avoid errors and enforces conventions.
- [ ] I will suggest you delete and restart your webpack configuration there is an error that occured during the setup, and I think it will be better to move the `package.json`, `package-lock.json` and `webpack.config.js` files to the root of your project and not in the `src` folder

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by BrianSammit — APPROVED** [review]
# STATUS: APROVED :green_circle: :clap: 

Hello @vanillainanutshell, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
